name: Pipeline de CI-CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Corrigido: uses e versão v4
      
      - name: Setup Node
        uses: actions/setup-node@v4 # Corrigido: actions no plural
        with:
          node-version: 18
          
      - run: npm install
      
      # Vamos apenas rodar o index.js para testar, em vez do npm test
      - name: Executar Automacao
        run: node index.js 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (simulado)
        run: echo "Deploy realizado com sucesso"
