name: Pipeline de CI-CD

on:
  push:
    branches: [master]

# Adicionamos isso para forçar o uso do Node 24 e remover o aviso
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Atualizamos a versão do seu código para 24 também
          
      - run: npm install
      
      - name: Executar Automacao
        run: node index.js 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (simulado)
        run: echo "Deploy realizado com sucesso no cliente com a API_TOKEN ${{ secrets.API_TOKEN }}"
