name: Pipeline Node e Python
on:
  push:
    branches: [ "master" ] # Verifique se sua branch principal é master ou main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4
      
      # --- SETUP NODE.JS ---
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Versão mais estável atualmente
          cache: 'npm' # Agiliza os próximos pushes salvando as dependências

      - name: Instalar dependencias
        run: npm install

      - name: Executar script Node
        run: node index.js

      # --- SETUP PYTHON ---
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Validar scripts Python
        run: python -m compileall .
